name: Build and deploy Quasar app to Azure Web App - ansalemo-vue-blog-test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      - name: Install dependencies and build Quasar app
        run: |
          npm install
          quasar build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: quasar-app
          path: dist/spa

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      URL: $  # Replace with your Azure Web App URL

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: quasar-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'detikideal'  # Replace with your Azure Web App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
